//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitchell_International.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Car
    {
        [Required]
        public int Id { get; set; }
        [Range(1950,2050,ErrorMessage ="Value of {0} must be between {1} - {2}.")]
        [Required]
        public int Year { get; set; }

        [RegularExpression(@"^[a-zA-Z0-9]*$", ErrorMessage = "Please enter a valid {0}.")]
        [Required]
        public string Make { get; set; }

        [RegularExpression(@"^[a-zA-Z0-9""'\s-]*$",ErrorMessage ="Please enter a valid {0}.")]
        [Required]
        public string Model { get; set; }
    }
}
